const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const poster=$('#poster'), photo=$('#photoImg'), placeholder=$('#placeholder'), mark=$('#mark'), fallbackMark=$('#fallbackMark'), customMark=$('#customMark');
const defaults={format:'youtube',layout:'editorial',headline:'MITÄ LAADUKAS\nHARJOITTELU\nOIKEASTI VAATII?',accent:'HARJOITTELU',guestName:'KALLE MÄENHARJU',guestRole:'LIIKUNTALÄÄKETIETEEN KANDIDAATTI',episode:'01',topics:'URHEILU · TERVEYS · SUORITUSKYKY',posX:68,posY:50,zoom:112,brightness:82,contrast:118,grayscale:18,warmth:7,markOpacity:9,markScale:110,markX:0,markY:0,photoData:'',markData:''};
let persisted={};
try{persisted=JSON.parse(localStorage.getItem('capraCastState')||'{}')}catch(e){}
let state={...defaults,...persisted,photoData:'',markData:''};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function highlight(text,term){let safe=esc(text).replace(/\n/g,'<br>');if(!term)return safe;const t=esc(term);try{return safe.replace(new RegExp(t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig'),m=>`<span class="accent">${m}</span>`)}catch(e){return safe}}
function save(){const clean={...state};delete clean.photoData;delete clean.markData;try{localStorage.setItem('capraCastState',JSON.stringify(clean))}catch(e){}}
function syncInputs(){['headline','accent','guestName','guestRole','episode','topics'].forEach(k=>$('#'+k).value=state[k]);['posX','posY','zoom','brightness','contrast','grayscale','warmth','markOpacity','markScale','markX','markY'].forEach(k=>$('#'+k).value=state[k]);$$('.format-btn').forEach(b=>b.classList.toggle('active',b.dataset.format===state.format));$$('.layout-btn').forEach(b=>b.classList.toggle('active',b.dataset.layout===state.layout))}
function render(){poster.dataset.format=state.format;poster.className=`poster layout-${state.layout}`;if($('#safeToggle').checked)poster.classList.add('show-safe');$('#headlineOut').innerHTML=highlight(state.headline,state.accent);$('#guestNameOut').textContent=state.guestName;$('#guestRoleOut').textContent=state.guestRole;$('#epOut').textContent=String(state.episode).padStart(2,'0');$('#topicsOut').textContent=state.topics;photo.src=state.photoData||'';placeholder.style.display=state.photoData?'none':'grid';photo.style.objectPosition=`${state.posX}% ${state.posY}%`;photo.style.transform=`scale(${state.zoom/100})`;photo.style.filter=`brightness(${state.brightness}%) contrast(${state.contrast}%) grayscale(${state.grayscale}%) sepia(${state.warmth}%)`;mark.style.opacity=state.markOpacity/100;mark.style.transform=`translate(${state.markX}%,${state.markY}%) scale(${state.markScale/100})`;if(state.markData){customMark.src=state.markData;customMark.hidden=false;fallbackMark.style.display='none'}else{customMark.hidden=true;fallbackMark.style.display='block'}updateRangeOutputs();fit();save()}
function updateRangeOutputs(){$$('.range-row').forEach(r=>{const i=r.querySelector('input'),o=r.querySelector('output');if(!i||!o)return;let v=i.value;if(['zoom','brightness','contrast','grayscale','warmth','markOpacity','markScale'].includes(i.id))v+='%';o.value=v;o.textContent=v})}
function fit(){const stage=$('.stage-wrap'), shell=$('.preview-shell');if(!stage||!poster)return;const pad=window.innerWidth<880?16:52;const availW=Math.max(260,stage.clientWidth-pad),availH=window.innerWidth<880?Math.min(window.innerHeight*.68,720):Math.max(340,window.innerHeight-pad);const s=Math.min(availW/poster.offsetWidth,availH/poster.offsetHeight,1);$('#scale').style.transform=`scale(${s})`;shell.style.width=(poster.offsetWidth*s)+'px';shell.style.height=(poster.offsetHeight*s)+'px'}
$$('.format-btn').forEach(b=>b.onclick=()=>{state.format=b.dataset.format;render()});
$$('.layout-btn').forEach(b=>b.onclick=()=>{state.layout=b.dataset.layout;render()});
['headline','accent','guestName','guestRole','episode','topics'].forEach(k=>$('#'+k).addEventListener('input',e=>{state[k]=e.target.value;render()}));
['posX','posY','zoom','brightness','contrast','grayscale','warmth','markOpacity','markScale','markX','markY'].forEach(k=>$('#'+k).addEventListener('input',e=>{state[k]=+e.target.value;render()}));
$('#safeToggle').addEventListener('change',render);
function loadImageFile(file,key){if(!file)return;const r=new FileReader();r.onload=()=>{state[key]=r.result;render()};r.readAsDataURL(file)}
$('#photoInput').addEventListener('change',e=>loadImageFile(e.target.files[0],'photoData'));
$('#markInput').addEventListener('change',e=>loadImageFile(e.target.files[0],'markData'));
$$('.preset-btn').forEach(b=>b.onclick=()=>{if(b.dataset.preset==='core')Object.assign(state,{brightness:82,contrast:118,grayscale:18,warmth:7});if(b.dataset.preset==='bw')Object.assign(state,{brightness:84,contrast:128,grayscale:100,warmth:0});if(b.dataset.preset==='warm')Object.assign(state,{brightness:88,contrast:116,grayscale:8,warmth:18});syncInputs();render()});
$('#reset').onclick=()=>{state={...defaults,photoData:state.photoData,markData:state.markData};syncInputs();render()};
async function capture(format=state.format){const prev=state.format,safe=$('#safeToggle').checked;state.format=format;$('#safeToggle').checked=false;render();if(document.fonts&&document.fonts.ready)await document.fonts.ready;await new Promise(r=>setTimeout(r,100));const canvas=await html2canvas(poster,{backgroundColor:null,scale:1,useCORS:true,logging:false});state.format=prev;$('#safeToggle').checked=safe;render();return canvas}
function canvasBlob(canvas,type='image/png',quality=1){return new Promise(resolve=>canvas.toBlob(resolve,type,quality))}
function dlBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
$('#download').onclick=async()=>{const b=$('#download');b.disabled=true;b.textContent='Viedään…';try{const c=await capture(state.format),blob=await canvasBlob(c);dlBlob(blob,`capra-cast-${state.format}-${state.episode}.png`)}catch(e){alert('Vienti epäonnistui. Kokeile päivittää sivu ja uudelleen.')}finally{b.disabled=false;b.textContent='Tallenna PNG'}};
$('#downloadAll').onclick=async()=>{const b=$('#downloadAll');b.disabled=true;b.textContent='Rakennetaan ZIP…';try{const zip=new JSZip();for(const f of ['youtube','instagram','reels','tiktok']){b.textContent=`Viedään ${f}…`;const c=await capture(f),blob=await canvasBlob(c);zip.file(`capra-cast-${f}-${state.episode}.png`,blob)}const out=await zip.generateAsync({type:'blob'});dlBlob(out,`capra-cast-${state.episode}-kaikki-koot.zip`)}catch(e){alert('ZIP-vienti epäonnistui. Voit viedä koot myös yksittäin.')}finally{b.disabled=false;b.textContent='Vie kaikki 4 kokoa ZIP'}};
window.addEventListener('resize',fit);syncInputs();render();